name: test-build

on: [push, pull_request]

jobs:

  build:

    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Environment
        run: |
          bash
          set -x
          uname -a
          git branch 
          ls -alt
          whoami || true
          sysctl -a | grep machdep.cpu || true
          system_profiler SPHardwareDataType | grep " Memory:" || true
          ls -alt /usr/bin | grep -i xcode
          gcc --version || true
          which brew || true
          brew --version || true
          sw_vers || true
          which autoconf || true
          which make || true
          which automake || true
          brew install autoconf automake libtool
          brew install argp-standalone
          brew ls argp-standalone
          which make || true
          which automake || true
          which autoconf || true
          which libtool || true
          export DRAGON_BASE_DIR=$PWD/src
          source .github/workflows/setup
          source hack/setup
          source hack/clean_build
          find / 2>&1 | grep -v denied | grep -e tar.gz$ -e whl$ | grep dragon || true
          #
          # sudo apt update
          # sudo apt install podman -y
          # podman --version
          # podman run hello-world
          # my_container=$(podman run -v $PWD:/workspace -d --shm-size=4gb --rm -it quay.io/pypa/manylinux2014_x86_64)
          # echo $my_container
          # podman exec $my_container ls -alt
          # podman exec $my_container ls -alt /workspace
          # podman exec $my_container bash -c "cd /workspace && git status"
          # podman exec $my_container bash -c "cd /workspace && ./dst/runBuildPrep.py312.sh"
          # podman exec $my_container bash -c "cd /workspace && ./dst/runBuild.sh"
          # podman exec $my_container bash -c "cd /workspace && ./dst/runUnitTest.sh"
          # ls -alt src/release/dragon*tar.gz
          # podman ps -a
          # podman kill $my_container
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dragon-macos-pkg
          path: src/dist/dragonhpc*whl
          # sample path: src/dist/dragonhpc-0.13.1-cp314-cp314-macosx_26_0_arm64.whl
          # sample runner absolute path: /Users/runner/work/dragon/dragon/src/...
